### ISSUE TITLE
Stance classification system message missing

### ISSUE THREAD

**Issue by bendavidsteel** [Armaniii/WIBA#1]
Hi,

Thanks for the nice GitHub repo. I'm trying to figure out the system messages for the 3 HF models. I've found the system messages for the argument detection and target extraction models you placed as .txts in the data directory, but find no indication of what you used for the stance classification model. In the finetune.py file, it implies you used the argument detection system message for all models which I presume is not the case?

Thanks in advance for the help!

**Comment by Armaniii** [comment]
Hello,
For Stance, we do in fact use the **same** system message as a the Detect and Extract models, as it demonstrates the most improvement through various testing. It is an interesting observation, and perhaps counter-intuitive and we make a note of it in the associated WIBA paper (pg. 5):

> **Argument Stance Formalization.** After thorough experimentation of possible interpretations of a stance version of
> our Argument Transition Network, we find that the same ATN used for Detection performs the best for Stance as well. We
> therefore rely on the ATN logic in Figure 2 for WIBA-Stance. 

Hopefully we can perform a more thorough investigation into the prompt engineering and ATN logic in the future to further explore this! Please let me know if you have any other questions!

**Comment by bendavidsteel** [comment]
Ah thank you! Should have read the paper more closely:) Classic counter-intuitive prompting outcome.
